[package]
name = "longship"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-ansi-term = "0.49"
rayon = "1.10.0"
regex = "1.11.1"
