name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build binary
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            cargo build --release --target ${{ matrix.target }}
            BIN_PATH=target/${{ matrix.target }}/release
          else
            cargo build --release
            BIN_PATH=target/release
          fi

          BIN_NAME=$(basename $(pwd))
          mkdir -p dist
          cp $BIN_PATH/$BIN_NAME dist/${BIN_NAME}-${{ matrix.target }}
          cd dist
          tar -czvf ${BIN_NAME}-${{ matrix.target }}.tar.gz ${BIN_NAME}-${{ matrix.target }}
          shasum -a 256 ${BIN_NAME}-${{ matrix.target }}.tar.gz > ${BIN_NAME}-${{ matrix.target }}.tar.gz.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: dist/

release:
  name: Upload to GitHub Release
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Copy release files
      run: |
        mkdir release

        # Linux artifacts
        cp artifacts/x86_64-unknown-linux-gnu/*.tar.gz release/
        cp artifacts/x86_64-unknown-linux-gnu/*.sha256 release/

        # macOS artifacts
        cp artifacts/x86_64-apple-darwin/*.tar.gz release/
        cp artifacts/x86_64-apple-darwin/*.sha256 release/
    - name: List downloaded artifacts
      run: ls -R artifacts
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
